### ISSUE TITLE
Nonsense (negative) steps/km and steps/hour values

### ISSUE THREAD

**Issue by flocsy** [wwarby/walker#7] opened 2022-04-24 15:30 UTC
Last week I used the Hike activity for the first time, with Walker DF. Some of the activity data I see in the GCM android app has nonsense values, i.e:
The y axis of the steps/km graph have values between: -104,818 and 2,002,850. Now it is possible that it was meant to be -104.818 to 2002.850 (aka 1/1000th), but even that makes no sense: first and foremost: what does a negative steps/km value mean? Secondly why confuse the user with millisteps/km?
Same with the steps/hour: -326 to 6,855. What is the negative value?

https://photos.app.goo.gl/49HykmHwbHCzyUWz6

**Comment by wwarby** [comment] 2022-04-25 13:09
Hi @flocsy, thanks for the feedback. That's definitely not intended behaviour. I'm pretty sure the two issues you've raised are directly related to one another - I've heard before that resuming an activity makes things go a bit screwy with Walker, but I can't remember now whether I ever looked into the problem.

The negative values are almost certainly just a weird side effect of the underlying fault - essentially how Walker counts steps for an activity is to look at the total steps for the current day when you start the activity, and then re-request total daily steps during the activity and subtract one from the other. From memory I think I had to do something to work around the possibility that an activity crossed midnight and therefore daily steps reset. Steps/km and Steps/hour are derived in a similar way, so if I'm losing track of step counts during a paused activity it doesn't surprise me that everything step-related after that is in a mess.

I'll try to devote some time this weekend to looking into the problem.

**Comment by flocsy** [comment] 2022-04-27 16:14
I just did a test now:

Start, walk a few steps, stop, wait a few seconds, resume => steps continued to count

Start, walk a few steps, stop, resume later, wait a few seconds, start (which basically is resume) => I thought it will show 0. But no! It did show the previous step count, however when I clicked start then it changed it to 0.

So it look like you'll need to detect if it's the beginning of the activity or the continuation, but it's pretty simple, you just need to look at the time (because that's displayed correctly even after the resume later), if it's not 0 then it's continued. You might also need to save the total daily steps when the activity starts, and then use that if/when it is resumed.

**Comment by wwarby** [comment] 2022-04-27 17:10
Great, thanks for testing that. Fingers crossed I can introduce a fix without blowing the memory limit on the older 16K devices otherwise that bug is going to have to remain in place for those devices forever (or I'll have to find some memory savings elsewhere, which will be hard).

**Comment by flocsy** [comment] 2022-04-27 18:09
I see in the code that in theory it should work because in WalkerApp.onStop you save it. So it might need some debugging. If you don't manage to reproduce it, let me know if you need debugging (I have Fenix6 or Forerunner245, it happened on the F6) maybe it behaves differently on F6?

I think there are another bugs:
WalkerView:100: stepsActivityField.setData(0);
shouldn't this be set to steps instead of 0?

And here's one for sure which is also related:
WalkerView:166: stepsWhenTimerBecameActive = ActivityMonitor.getInfo().steps;
When I saw this I did the following test and unfortunately I was right:
Start, do a few steps, stop moving, wait a few seconds until the steps counter doesn't change any more, remember the number of steps, stop the activity, do a few steps, resume activity, and you'll see that the steps count is not what you remember. The steps you did while the activity was paused is also included.

So I think the fix will be a fit more complicated. I guess you'll really need to make sure that the steps are saved when the app closes and load that on start (as now, at least that's what I see in the code) but also you'll need to "adjust" stepsWhenTimerBecameActive and do something like:

stepsWhenTimerBecameActive = ActivityMonitor.getInfo().steps - previousSteps;

Maybe previousSteps == consolidatedSteps? Not sure, probably not, but rather in initialize you should do:

steps = app.getProperty("as");
if (steps == null) { steps = 0; }
previousSteps = steps;

I even see now that you have this already in WalkerView:83: if (info != null && info.elapsedTime > 0) {

So I think I know the problem: when I stop, and some time later resume, then the activity automatically starts, so in initialize you get the positive time and everything is good. But when I stop, then resume later, then start, then it displays the screen of walker, but it's not started. I have to press start to actually resume the activity. I don't know if this is intended or maybe it's a bug in Fenix 6. Anyway I guess, that you'll need to move some of the code from initialize to timerStart.

And there's one more "suspicious" thing: onTimerStart and onTimerResume does the same and also onTimerStop and onTimerPause. Maybe there you'll need to debug as well and see if different things are needed.

**Comment by wwarby** [comment] 2022-04-27 19:07
Sounds like you’re more familiar with the code than me at this point - I don’t think I’ve looked at it for about 18 months ;)

really appreciate your input - it’ll be the weekend at least before I start poking around in there but I intend to give it a day of my attention and I’ll review everything you’ve suggested.

**Comment by wwarby** [comment] 2022-05-13 13:17
Hi @flocsy, just wanted to give you a quick update. I incorporated your localisation changes over the weekend except for the localisation of unit abbreviations, which I will need to make space for on the 16KB devices or otherwise branch the resource files to keep the current implementation for 16KB devices. I haven't released that change yet because I want to get to all the other things you've raised. I've also moved myself off Eclipse now, so working on this codebase going forward will be much more pleasant.

The next thing I want to tackle is the stop/resume functionality bug, which needs to be fixed on 16KB devices as well - I'm gonna incorporate your suggestion for improving the circular queue efficiency too. Once I've got that stuff working correctly and tested, I'll move on to branching the implementation for 16KB devices so that I can support the 8 colour watch models. None of this is going to take all that long, I'm just very short on free time at the moment. I do really appreciate the engagement though, and intend to get all these suggestions implemented in the next couple or weeks or so.

Cheers.

**Comment by wwarby** [comment] 2022-06-22 15:42
I've solved this (I think). The fix was relatively simple, but I won't tell you how many times I had to pace up and down my kitchen stopping and starting my watch with between plugging it in to view debug logs before I had a solid grasp of the problem!

Releasing the fix shortly.

**Closed by wwarby** 2022-06-22 15:42 UTC
